#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements_lint.txt

ruff check . --fix;
pre-commit install-hooks --config .github/pre-commit-config.yaml;
pre-commit run --hook-stage manual --all-files --config .github/pre-commit-config.yaml;

vulture . --min-confidence 75 --ignore-names policy --exclude .venv/lib/python3.11/site-packages

mypy . --config-file mypy.ini